name: Build Training and Publish

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Latest Skeleton Version
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            quay.io/acend/prometheus-training-spring-boot-example:skeleton-pr-${{ github.event.pull_request.number }}
      -
        name: Build Latest Solution Version
        uses: docker/build-push-action@v3
        with:
          context: ./solution
          file: ./solution/Dockerfile
          push: false
          tags: |
            quay.io/acend/prometheus-training-spring-boot-example:pr-${{ github.event.pull_request.number }}